FROM fedora:25

ENV PATH="$PATH:/root/.cargo/bin" \
    GOPATH=/tmp \
    MERCATOR_PYTHON=python3

RUN dnf install -y ghc-ghc ghc-Cabal cabal-install cmake openssl-devel ruby java-devel maven which mono-devel python3 git golang glide make npm nuget && dnf clean all

# install test requirements
RUN pip3 install behave

# install stable rust & build deps for cargo
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y 

# fix them NuGets certificates
RUN yes | certmgr -ssl -m https://go.microsoft.com && yes | certmgr -ssl -m https://nuget.org

WORKDIR /mercator-go

COPY . /mercator-go

# Install mercator-go
RUN make all DOTNET=YES RUST=YES JAVA=YES HASKELL=YES GOLANG=YES

CMD ["/mercator-go/tests/runtest.sh"]
